name: backround_location_tracking
description: Background GPS location tracker with Hive storage and platform channels.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  geolocator: ^13.0.4
  permission_handler: ^11.4.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  intl: ^0.20.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
